storage:
  extends:
    file: docker-compose-common.yml
    service: storage

data:
  extends:
    file: docker-compose-common.yml
    service: data

db:
  extends:
    file: docker-compose-common.yml
    service: db

node:
  extends:
    file: docker-compose-common.yml
    service: node
  volumes_from:
    - storage
    - data
  environment:
    NODE_RUN_ENV: local
  links:
    - db

buildtools:
  image: weyforth/nodejs-buildtools:1.0
  volumes_from:
    - storage
    - data
  environment:
    multi: spec=- mocha-text-cov=- html-cov=coverage.html
  links:
    - db
    - node
