storage:
  extends:
    file: docker-compose-common.yml
    service: storage

data:
  extends:
    file: docker-compose-common.yml
    service: data

db:
  extends:
    file: docker-compose-common.yml
    service: db

node:
  extends:
    file: docker-compose-common.yml
    service: node
  volumes_from:
    - storage
    - data
  links:
    - db
  environment:
    NODE_RUN_ENV: local
